spring:
  datasource:
    url: jdbc:postgresql://database-channels-service:5432/channels-db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
